"""FastAPI application factory / ASGI entrypoint (`uvicorn app.main:app`)."""

import logging
from collections.abc import AsyncIterator
from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.config import get_settings
from app.database.init_db import init_database
from app.database.session import engine
from app.middleware.error_handlers import register_exception_handlers
from app.middleware.request_context import RequestContextMiddleware
from app.routers import api_router
from app.services.coingecko_service import CoinGeckoService
from app.services.neon_auth_service import NeonAuthVerifier

settings = get_settings()
logging.basicConfig(
    level=logging.DEBUG if settings.DEBUG else logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s: %(message)s",
)
logger = logging.getLogger(__name__)


@asynccontextmanager
async def lifespan(app: FastAPI) -> AsyncIterator[None]:
    coingecko = CoinGeckoService(settings)
    neon_auth = NeonAuthVerifier(settings)
    app.state.coingecko = coingecko
    app.state.neon_auth = neon_auth
    if settings.AUTO_INIT_DB:
        await init_database(coingecko)
    logger.info(
        "%s started (env=%s, docs=/docs, Google/GitHub sign-in %s)",
        settings.APP_NAME,
        settings.APP_ENV,
        "enabled" if neon_auth.enabled else "disabled",
    )
    yield
    await neon_auth.aclose()
    await coingecko.aclose()
    await engine.dispose()


OPENAPI_TAGS = [
    {"name": "Santé", "description": "Vérification de l'API, de PostgreSQL et de CoinGecko."},
    {"name": "Authentification", "description": "Inscription, connexion (JWT) et utilisateur courant."},
    {"name": "Cryptomonnaies (CoinGecko)", "description": "Données de marché proxifiées et mises en cache."},
    {"name": "Portefeuille", "description": "Valorisation, historique des transactions, snapshots."},
    {"name": "Trading", "description": "Achats et ventes virtuels au prix CoinGecko courant."},
    {"name": "Classement", "description": "Classement global calculé côté serveur."},
    {"name": "Profil", "description": "Profil et statistiques du joueur connecté."},
]

app = FastAPI(
    title=settings.APP_NAME,
    version="1.0.0",
    description=(
        "API du jeu de simulation de trading **Crypto Arena** : argent virtuel, prix réels CoinGecko, "
        "classement entre joueurs. Aucun argent réel n'est utilisé."
    ),
    lifespan=lifespan,
    openapi_tags=OPENAPI_TAGS,
)

# Middlewares: the last one added is the outermost. CORS must wrap everything so that
# error responses generated by RequestContextMiddleware also carry the CORS headers.
app.add_middleware(RequestContextMiddleware)
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.cors_origins_list,
    allow_credentials=True,
    allow_methods=["GET", "POST", "PATCH", "DELETE", "OPTIONS"],
    allow_headers=["Authorization", "Content-Type"],
)

register_exception_handlers(app)
app.include_router(api_router)


@app.get("/", include_in_schema=False)
async def root() -> dict[str, str]:
    return {"name": settings.APP_NAME, "docs": "/docs", "health": "/api/health"}
